############################################################
# Project Metadata
# Manages the hole project metadata
############################################################
group=de.lennarkoe.label4j
artifact=label4j
prefix=l4j
version=2.1.0

authors=[lennarkoe;Lennard;leycm@proton.me]
description=A fast, server-side translation and label provider for high-performance Text & MiniMessage localization.
remote=https://codeberg.org/lennarkoe/label4j

version-catalog=gradle/libs.versions.toml
version-java=21